### ISSUE TITLE
whisper已经下载到本地了，就是找不到加载位置

### ISSUE THREAD

**Issue by MUFCLK** [LinkSoul-AI/LLaSM#3]
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/whisper-large-v2/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd9399957b0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 7b68228e-e6a6-4ecd-bc7e-3affc92e3ac3)')' thrown while requesting HEAD https://huggingface.co/openai/whisper-large-v2/resolve/main/config.json
Traceback (most recent call last):
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/liukai/LLaSM/infer.py", line 122, in <module>
    main(args)
  File "/work/liukai/LLaSM/infer.py", line 46, in main
    model = LlaaaLlamaForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/work/liukai/LLaSM/llasm.py", line 160, in __init__
    self.model = LlaaaLlamaModel(config)
  File "/work/liukai/LLaSM/llasm.py", line 41, in __init__
    self.audio_tower = [load_whisper(config.mm_audio_tower)]
  File "/work/liukai/LLaSM/llasm.py", line 28, in load_whisper
    model = WhisperModel.from_pretrained(audio_tower_name)
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2325, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 590, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/utils/hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/whisper-large-v2 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by waterpeople** [comment]
我也遇到这问题了，请问你解决了吗

**Comment by MUFCLK** [comment]
我解决了，你仔细看看报错的日志，有一个py文件中把路径写错了，你对应的改一下，改成你的路径就行了。

**Comment by moliwei2019** [comment]
请问楼主部署成功这个项目了吗，我运行提示我CUDA版本过低了，我是11.7的版本，请问最低要求版本是多少啊

**Comment by MUFCLK** [comment]
我的是CUDA 12.0的成功了

**Comment by moliwei2019** [comment]
好的，感谢

**Comment by mmccodes** [comment]
> '(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/whisper-large-v2/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd9399957b0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 7b68228e-e6a6-4ecd-bc7e-3affc92e3ac3)')' thrown while requesting HEAD https://huggingface.co/openai/whisper-large-v2/resolve/main/config.json Traceback (most recent call last): File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file resolved_file = hf_hub_download( File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download raise LocalEntryNotFoundError( huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/work/liukai/LLaSM/infer.py", line 122, in main(args) File "/work/liukai/LLaSM/infer.py", line 46, in main model = LlaaaLlamaForCausalLM.from_pretrained( File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained model = cls(config, *model_args, **model_kwargs) File "/work/liukai/LLaSM/llasm.py", line 160, in **init** self.model = LlaaaLlamaModel(config) File "/work/liukai/LLaSM/llasm.py", line 41, in **init** self.audio_tower = [load_whisper(config.mm_audio_tower)] File "/work/liukai/LLaSM/llasm.py", line 28, in load_whisper model = WhisperModel.from_pretrained(audio_tower_name) File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2325, in from_pretrained config, model_kwargs = cls.config_class.from_pretrained( File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 590, in from_pretrained config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs) File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs) File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict resolved_config_file = cached_file( File "/root/anaconda3/envs/llasm/lib/python3.10/site-packages/transformers/utils/hub.py", line 452, in cached_file raise EnvironmentError( OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/whisper-large-v2 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

vpn开全局可以解决

**Comment by wenqing-shang** [comment]
> Refe
请问，是哪行代码 的路径错了，
